export const STARTER_COLLECTION = {
  champions: [
    { id: "champ1", count: 1 },
    { id: "champ2", count: 1 },
    { id: "champ3", count: 1 },
    { id: "champ4", count: 1 },
    { id: "champ5", count: 1 },
    { id: "champ6", count: 1 },
    { id: "champ7", count: 1 },
    { id: "champ8", count: 1 },
    { id: "champ9", count: 1 },
  ],
  commands: [
    { id: "com1", val: 1, count: 2 },
    { id: "com1", val: 2, count: 1 },
    { id: "com1", val: 3, count: 1 },
    { id: "com2", val: 1, count: 2 },
    { id: "com2", val: 2, count: 1 },
    { id: "com2", val: 3, count: 1 },
    { id: "com3", val: 1, count: 2 },
    { id: "com3", val: 2, count: 1 },
    { id: "com3", val: 3, count: 1 },
    { id: "com4", val: 1, count: 2 },
    { id: "com4", val: 2, count: 1 },
    { id: "com4", val: 3, count: 1 },
    { id: "com5", val: 1, count: 2 },
    { id: "com5", val: 2, count: 1 },
    { id: "com5", val: 3, count: 1 },
  ],
  accessories: [{ id: "acc1", count: 1 }],
};
