const TITLE = "Standard Commands";

const ROUTE = "standard-coms";

const KEYS = [
  {
    key: "name",
    label: null,
    class: "list-basic",
  },
];

const LIST = [
  {
    id: "com1",
    name: "Fire",
    atr: "mag",
    mark: null,
    rare: false,
    val: 0,
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    pic: "/assets/com-art/fire1.png",
  },
  {
    id: "com2",
    name: "Blizzard",
    atr: "mag",
    mark: null,
    rare: false,
    val: 0,
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    pic: "/assets/com-art/blizzard1.png",
  },
  {
    id: "com3",
    name: "Thunder",
    atr: "mag",
    mark: null,
    rare: false,
    val: 0,
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    pic: "/assets/com-art/thunder1.png",
  },
  {
    id: "com4",
    name: "Aero",
    atr: "mag",
    mark: null,
    rare: false,
    val: 0,
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    pic: "/assets/com-art/aero1.png",
  },
  {
    id: "com5",
    name: "Cure",
    atr: "mag",
    mark: "healing",
    rare: false,
    val: 0,
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    pic: "/assets/com-art/cure1.png",
  },
  {
    id: "com6",
    name: "Combo Plus",
    atr: "spd",
    mark: "split",
    rare: false,
    val: 0,
    range: [0, 2, 4, 6, 8],
    pic: "/assets/com-art/combo1.png",
  },
  {
    id: "com7",
    name: "Quake",
    atr: "mag",
    mark: null,
    rare: false,
    val: 0,
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    pic: "/assets/com-art/stone1.png",
  },
  {
    id: "com8",
    name: "Cover Ally",
    atr: "mag",
    mark: "defending",
    rare: false,
    val: 0,
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    pic: "/assets/com-art/coverAlly1.png",
  },
  {
    id: "com9",
    name: "Barrier",
    atr: "mag",
    mark: "defending",
    rare: false,
    val: 0,
    range: [1, 3, 5, 7, 9],
    pic: "/assets/com-art/barrier1.png",
  },
  {
    id: "com10",
    name: "Dark Fire",
    atr: "mag",
    mark: "piercing",
    rare: false,
    val: 0,
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    pic: "/assets/com-art/darkFire1.png",
  },
  {
    id: "com11",
    name: "Triple Blizzaga",
    atr: "mag",
    mark: "split",
    rare: false,
    val: 0,
    range: [0, 6, 7, 8, 9],
    pic: "/assets/com-art/trippleBlizzaga1.png",
  },
  {
    id: "com12",
    name: "Zetta Flare",
    atr: "mag",
    mark: "piercing",
    rare: false,
    val: 0,
    range: [0, 6, 7, 8, 9],
    pic: "/assets/com-art/zettaFlare1.png",
  },
];

export const STANDARD_COMS = { ROUTE, TITLE, KEYS, LIST };
